spring:
  application:
    name: apigw
  profiles:
    active: local
  config:
    import: #optional:configserver:http://movie-config-service-1:8071
      optional:configserver:http://localhost:8071

management:
  endpoints:
    web:
      exposure:
        include: ['refresh','beans','env']